# General
url: https://devheart-css.vikpe.github.io
encoding: utf-8

# Github
repository: vikpe/devheart-css

# Handling Reading
safe: true
include:
  - _pages

exclude:
  - node_modules/
  - project/
  - src/
  - .gitignore
  - bs-config.js
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - gulpfile.paths.js
  - readme.md
  - yarn.lock

# Conversion
markdown: kramdown
incremental: false

# Outputting
permalink: pretty
timezone: Europe/Stockholm

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false

# Custom settings
custom_settings:
  name: Devheart CSS
  description: Simple, JavaScript-less front-end framework based on Bootstrap.
  repo_url: https://github.com/vikpe/devheart-css
  is_development: false
  is_published: true
  google_analytics_tracking_code: false
